apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
  namespace: logger

spec:
  replicas: 1
  revisionHistoryLimit: 2

  selector:
    matchLabels:
      app: app

  template:
    metadata:
      labels:
        app: app

    spec:
      containers:
      - name: app
        image: mazdermind/request-logger:v1

        env:
          - name:  DB_HOST
            value: postgres

          - name:  DB_NAME
            valueFrom:
              secretKeyRef:
                name: logger
                key: db-name

          - name:  DB_USER
            valueFrom:
              secretKeyRef:
                name: logger
                key: db-user

          - name:  DB_PASS
            valueFrom:
              secretKeyRef:
                name: logger
                key: db-pass

        ports:
        - containerPort: 5000
          name: web
          protocol: TCP
